### ISSUE TITLE
无法切换其他摄像头

### ISSUE THREAD

**Issue by Elsure** [xianfei/SysMocap#14]
当计算机连接多个摄像头时，没有选项可以切换摄像头以使用其他的摄像头进行面捕。

**Comment by xianfei** [comment]
It's available on version 0.5.1.

![Snipaste_2022-06-06_17-10-37](https://user-images.githubusercontent.com/8101613/172131965-8de7b26b-4e1d-47a9-99d9-1de45003f975.jpg)

**Comment by xianfei** [comment]
fixed on v0.5.1
