### ISSUE TITLE
Mac电脑摄像头调用不到，请问会是什么原因呢？

### ISSUE THREAD

**Issue by davidhefan** [xianfei/SysMocap#25]
<img width="717" alt="image" src="https://user-images.githubusercontent.com/13231750/174432726-ed924ddb-0c10-468e-b7f3-7c64511086a7.png">
系统版本如下：
<img width="524" alt="image" src="https://user-images.githubusercontent.com/13231750/174432737-b2ed9f7d-16d5-4c7c-9356-d6b764607164.png">
查了权限设置，应用已经赋予了摄像头权限。
请问可能会是什么原因导致的呢？

**Comment by xianfei** [comment]
这个呀 是因为你装了OBSb并且选择了OBS的虚拟摄像头  这个是OBS虚拟摄像头的画面  去设置里看一下摄像头选项里有没有不是OBS的那个选项
<img width="622" alt="WX20220619-143812@2x" src="https://user-images.githubusercontent.com/8101613/174469017-5c431328-41f5-4625-ad9c-97ef74385ab2.png">

**Comment by davidhefan** [comment]
十分感谢，已经解决了。
