### ISSUE TITLE
无法导入Vroid生成的VRM

### ISSUE THREAD

**Issue by lersh** [xianfei/SysMocap#26]
我尝试导入后，显示加载失败，这个模型我试过可以正常导入到UE4的，文件本身应该没有问题
[GirlA.zip](https://github.com/xianfei/SysMocap/files/8954141/GirlA.zip)

**Comment by xianfei** [comment]
在我电脑上是可以的，检查一下配置文件路径是不是对的，以及不要删除或移动vrm文件
<img width="820" alt="WX20220626-212811@2x" src="https://user-images.githubusercontent.com/8101613/175816410-f5d6090e-ac94-426c-bc6e-b66114d5a6cd.png">

**Comment by lersh** [comment]
ok，我试着换了一个目录，可以加载出来了 ，我估计是对某些路径的不支持？加载不出来时，我的vrm文件的路径是e:\#modelAssets\VRM，改到e:\就正常了。是不是对#符号不兼容？

**Comment by xianfei** [comment]
> ok，我试着换了一个目录，可以加载出来了 ，我估计是对某些路径的不支持？加载不出来时，我的vrm文件的路径是e:#modelAssets\VRM，改到e:\就正常了。是不是对#符号不兼容？

应该是  说实话我还没见过这个符号
