### ISSUE TITLE
安装软件跟运行源码摄像头不能使用

### ISSUE THREAD

**Issue by pickerOne** [xianfei/SysMocap#29]
摄像头采集的位置都有一张图片 让扫码二维码下载软件咋个回事呢 

![截屏2022-08-01 下午4 10 35](https://user-images.githubusercontent.com/12746421/182103600-b8537242-3e23-45a9-8689-f7c4d01ebc4c.png)

**Comment by xianfei** [comment]
应该是你电脑上有其他软件创建了虚拟摄像头，在设置里面选一下摄像头试试

**Comment by pickerOne** [comment]
可以了，确实有一个虚拟摄像头 但是在电脑上没有找到相关软件 不知道为什么会出现这个
