### ISSUE TITLE
windows运行源码需要nodeJs和python版本是多少

### ISSUE THREAD

**Issue by JackW987** [xianfei/SysMocap#30]
试了一下nodeJs 16.16.0 python 3.9报错
![image](https://user-images.githubusercontent.com/25745086/184537552-61d93d2d-be35-4c94-8a07-0a4978ccd99c.png)

**Comment by xianfei** [comment]
这个好像是半透明窗口的那个插件(electron-acrylic-window)的问题，如果不需要高斯模糊窗口可以把这个插件从package.json的dependencies中删掉

**Comment by xianfei** [comment]
移除了这个模块，不会有问题了
