### ISSUE TITLE
您好，我在macos上运行，报错了

### ISSUE THREAD

**Issue by KONEONE** [xianfei/SysMocap#4]
![image](https://user-images.githubusercontent.com/39909636/170900475-d6606118-29e7-4793-b782-cd9dd6f43596.png)

我的mac是macos10.15版本

**Comment by xianfei** [comment]
试试separate-mocap-and-render这个分支呢  这个我把启动参数删了  而且在macos上实测性能更好

**Comment by KONEONE** [comment]
额，可是我电脑啥都没有，还不知道你这个代码下载下来后怎么运行

**Comment by xianfei** [comment]
喔喔我在readme里面更新了一下说明，我打包好放百度网盘里面了你可以下来试试
链接: https://pan.baidu.com/s/1hlm2sfYbhiIcfPKMHELhKw?pwd=dg8m 提取码: dg8m

**Comment by KONEONE** [comment]
wow, 回复的这么快！还是向你学习。

**Comment by KONEONE** [comment]
非常棒，已经运行出来了！

**Comment by xianfei** [comment]
好的 我去把这个版本和主分支合并一下
