### ISSUE TITLE
无法通过http输出至OBS

### ISSUE THREAD

**Issue by HPDell** [xianfei/SysMocap#5]
系统 Windows 11
软件版本 0.4.6

![image](https://user-images.githubusercontent.com/17842185/170970169-05949461-e79a-4e55-80ce-482d81e6adb9.png)

软件内设置开启通过 http/websocket 转发，端口8080，在 OBS 添加浏览器源，地址 http://127.0.0.1:8080/ 但是无法加载到页面。使用浏览器打开，依然无法打开页面。

**Comment by xianfei** [comment]
这是个bug  就是Readme里面有写到“Forwarding only support VRM”  目前vrm格式模型没问题  过两天我修复一下

**Comment by HPDell** [comment]
感谢up回复。但是VRM模型好像也有问题。如图

![image](https://user-images.githubusercontent.com/17842185/170998137-e493b381-2e10-46b4-8573-4d4ffead33da.png)

我试了几个VRM模型，都无法输出到OBS。

**Comment by xianfei** [comment]
这个我就不知道了   在设置勾一下devtools入口右上角点击去看看有没有报错吧  或者在cmd里运行这个看看有没有输出什么

**Comment by Aru321** [comment]
解决了吗，我也有这个问题，OBS浏览器源没画面

**Comment by notgoodpeople** [comment]
我也有类似的问题。在Chrome浏览器里打开 http://127.0.0.1:8080/ 是能显示的，但是OBS里不行。

**Comment by lersh** [comment]
我也有这个问题，在Chrome浏览器里打开 http://127.0.0.1:8080/ 是能显示的，但是OBS里不行。OBS的画面里会有VR NOT Support和AR Not Support的字样

**Comment by yukismimi** [comment]
源代码中有几处调用structuredClone API的地方需要修改一下。
OBS指定浏览器时会下载代码并在OBS中的Chrome驱动去运行的，OBS的Chrome驱动应该是75版本，暂不支持structuredClone API（需要98版本以上）
不考虑性能问题可以使用下面方式解决该问题。
JSON.parse(JSON.stringify(XXX))

**Comment by xianfei** [comment]
> 源代码中有几处调用structuredClone API的地方需要修改一下。 OBS指定浏览器时会下载代码并在OBS中的Chrome驱动去运行的，OBS的Chrome驱动应该是75版本，暂不支持structuredClone API（需要98版本以上） 不考虑性能问题可以使用下面方式解决该问题。 JSON.parse(JSON.stringify(XXX))

感谢  已修复
