### ISSUE TITLE
报错mica-electron work only on windows 11

### ISSUE THREAD

**Issue by aoaoms** [xianfei/SysMocap#50]
windows10 系统，应用主界面点击模型就报错误提示框。
mica-electron最新的版本已经支持windows 10 。

**Comment by xianfei** [comment]
Hi  我目前没有win10的系统  我先把Win10下的mica-electron禁用掉发布一个release吧  之后装个虚拟机测一下

在设置 中 关闭 使用毛玻璃效果  应该是可以凑合用的

**Comment by aoaoms** [comment]
> Hi 我目前没有win10的系统 我先把Win10下的mica-electron禁用掉发布一个release吧 之后装个虚拟机测一下
> 
> 在设置 中 关闭 使用毛玻璃效果 应该是可以凑合用的

嗯，关闭可以用。谢谢
