### ISSUE TITLE
win10，打开就是白屏

### ISSUE THREAD

**Issue by liquorLiu** [xianfei/SysMocap#58]
![图片](https://github.com/xianfei/SysMocap/assets/125868659/4a95b637-a9bb-41e5-9bf3-44bb3919662b)
依赖都用cnpm安装了一遍，但是打开就是白屏什么都没有。。

**Comment by xianfei** [comment]
在main.js中取消注释 第161行`// mainWindow.webContents.openDevTools()` 看看有没有报错

**Comment by liquorLiu** [comment]
![图片](https://github.com/xianfei/SysMocap/assets/125868659/26e20322-bc16-4a7c-812b-e9fe6fbd0a7a)
![图片](https://github.com/xianfei/SysMocap/assets/125868659/a06e6828-8b09-4eda-b720-b3a4a23f10ef)


> 在main.js中取消注释 第161行`// mainWindow.webContents.openDevTools()` 看看有没有报错

**Comment by xianfei** [comment]
> ![图片](https://private-user-images.githubusercontent.com/125868659/295481989-26e20322-bc16-4a7c-812b-e9fe6fbd0a7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTIxNTIsIm5iZiI6MTcwNDk1MTg1MiwicGF0aCI6Ii8xMjU4Njg2NTkvMjk1NDgxOTg5LTI2ZTIwMzIyLWJjMTYtNGE3Yy04MTJiLWU5ZmU2ZmJkMGE3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwNTQ0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGE2YTg0YjUyYWI0Y2VjZjYzMzEyNzZlMmFmZWQxNzJhM2FmZjZhODYxMTRmZjJhYmViNWJkYWNjYjY2NWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.edj7ApXFSFz6pfwNWhfjIgE5lIuJVXLqXL88VLP3qvM) ![图片](https://private-user-images.githubusercontent.com/125868659/295482052-a06e6828-8b09-4eda-b720-b3a4a23f10ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTIxNTIsIm5iZiI6MTcwNDk1MTg1MiwicGF0aCI6Ii8xMjU4Njg2NTkvMjk1NDgyMDUyLWEwNmU2ODI4LThiMDktNGVkYS1iNzIwLWIzYTRhMjNmMTBlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwNTQ0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2IxOThjNjc2MGM0NWUyN2E4ZmJiYTk2Njg1MzdlNDExN2UxNzcxZWI2OWY5ZmUzYjExMWJjNWQyZWY4MWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TG3R6Bel4hqpgTBjQCadnQlNk66gFaSt-oBPwvaExgY)
> 
> > 在main.js中取消注释 第161行`// mainWindow.webContents.openDevTools()` 看看有没有报错

看起来像是依赖包material color utilities的问题，感觉依赖没有装好，我没有试过cnpm，试试把node modules删了然后npm重新安装试试呢？

**Comment by liquorLiu** [comment]
我又尝试了重新下载依赖，electron需要用cnpm下载。其余的使用npm下载，成功运行了
