### ISSUE TITLE
可否支持输出视频？

### ISSUE THREAD

**Issue by Jockz** [xianfei/SysMocap#6]
感谢up主开源这么好的软件，提个小小建议，可否将3d人物的渲染视频进行导出，再次感谢up主的好软件

**Comment by but-cat** [comment]
up不需要那么麻烦呀，用下`MediaRecorder`这个API就能直接录制canvas或video媒体流，写起来很快的～

**Comment by xianfei** [comment]
> up不需要那么麻烦呀，用下`MediaRecorder`这个API就能直接录制canvas或video媒体流，写起来很快的～

emmmm我不太熟诶  有空我查查或者你要是不忙你也可以试试

**Comment by xianfei** [comment]
已支持
