### ISSUE TITLE
导入从Vroid Studio 1.28.2导出的 .vrm 文件无法加载

### ISSUE THREAD

**Issue by ZackZhao233** [xianfei/SysMocap#61]
使用 Vroid Studio 1.28.2 制作模型并导出 .vrm 文件后导入模型库一直显示loading，日志显示如下。

vue.js:9323 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
vue.js:9330 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
modelview.html:302 {"model":{"name":"test","type":"vrm","picBg":"","path":"C:/Users/wszwb/Desktop/test.vrm","accessories":{},"binding":{}},"backgroundColor":"#dee0ff","color":"#4355b9","textColor":"#00105c","useGlass":true}
three.js:35986 THREE.WebGLRenderer: .shadowMapEnabled is now .shadowMap.enabled.
set @ three.js:35986
Show 1 more frame
Show less
modelview.html:533 Loading model... Infinity %
modelview.html:533 Loading model... Infinity %
modelview.html:533 Loading model... Infinity %
modelview.html:533 Loading model... Infinity %
modelview.html:533 Loading model... Infinity %
modelview.html:533 Loading model... Infinity %
modelview.html:533 Loading model... Infinity %
modelview.html:533 Loading model... Infinity %
three-vrm.js:3253 Uncaught (in promise) Error: Could not find VRM extension on the GLTF
    at VRMImporter.<anonymous> (three-vrm.js:3253:27)
    at Generator.next (<anonymous>)
    at three-vrm.js:58:75
    at new Promise (<anonymous>)
    at __awaiter (three-vrm.js:54:16)
    at VRMImporter.import (three-vrm.js:3251:20)
    at VRM.<anonymous> (three-vrm.js:3332:45)
    at Generator.next (<anonymous>)
    at three-vrm.js:58:75
    at new Promise (<anonymous>)
lil-gui.umd.min.js:8 Uncaught TypeError: Cannot read properties of null (reading 'visible')
    at m.add (lil-gui.umd.min.js:8:26005)
    at modelview.html:571:24
add @ lil-gui.umd.min.js:8
(anonymous) @ modelview.html:571
Show 1 more frame
Show less

**Comment by xianfei** [comment]
看起来是three-vrm.js解析VRM的问题，我也尝试一下，有可能是新版本Vroid Studio生成的VRM格式太新了，当前使用的three-vrm.js解析不了

**Comment by xianfei** [comment]
<img width="601" alt="Snipaste_2024-07-02_15-55-21" src="https://github.com/xianfei/SysMocap/assets/8101613/f5ee76e0-30cf-4f25-8383-6287c9eff538">
<img width="950" alt="image" src="https://github.com/xianfei/SysMocap/assets/8101613/e13284f0-991f-47d4-a7bd-ab81fc326890">

目前是只支持VRM0，暂时不支持VRM1

**Comment by xianfei** [comment]
v0.7.x添加了vrm-1.0的支持
